name: "dbt action"
description: "Run and schedule dbt commands directly in your Github repo"
author: "Michael Whitaker"

inputs:
  dbt_command:
    description: "dbt command"
    default: "dbt run --profiles-dir ."
    required: true
  dbt_project_folder:
    description: "dbt project folder. Defaults to ."
    default: "."
    required: false
  dbt_profiles_folder:
    description: "dbt profiles folder. Defaults to ."
    default: "."
    required: false
  dbt_pr_schema:
    description: "dbt unique schema name."
    default: ".GITHUB_ACTION_PR_0000"
    required: true
outputs:
  result:
    description: "Success or failure of the dbt command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dbt_command }}
branding:
  icon: 'database'  
  color: 'purple'